### PR TITLE
Implement Point-Light Tracing

### PR DESCRIPTION
**Pull request by andreasala98**
This pull request is to keep track of the implementation of Point Light Tracing, a quink rendering algorithm. As this is a secondary feature for our project, we will implement this when we have time.

### CODE REVIEW

**Comment by PietroKlausner** [comment]
I'm sure the quickRayIntersection method for Box shapes can be optimized. Maybe @TommasoArmadillo can offer some precious insights.

**Comment by andreasala98** [comment]
> I'm sure the quickRayIntersection method for Box shapes can be optimized. Maybe @TommasoArmadillo can offer some precious insights.

He is the CEO of Boxes, after all.

**Comment by TommasoArmadillo** [comment]
Hi! @PietroKlausner, yes the could be optimized. In fact we don't need to compute all the intersections and then return `true` only if there is one or more intersections, but we can avoid some calculations. I just pushed a commit with this optimization. All the tests still pass correctly as expected!

**Comment by PietroKlausner** [comment]
> Hi! @PietroKlausner, yes the could be optimized. In fact we don't need to compute all the intersections and then return `true` only if there is one or more intersections, but we can avoid some calculations. I just pushed a commit with this optimization. All the tests still pass correctly as expected!

Thank you very much!

**Pull request merged**
